#ifndef _SQLSLAVE_H
#define _SQLSLAVE_H

#include "alloc.h"

#define SQL_OPTION_MAX		SBUF_SIZE
#define SQLQUERY_MAX_STRING	LBUF_SIZE

#define SQLDB_SLOT_HOSTNAME	1
#define SQLDB_SLOT_DBNAME	2
#define SQLDB_SLOT_USERNAME	3
#define SQLDB_SLOT_PASSWORD	4
#define SQLDB_SLOT_SOCKET   5
#define SQLDB_SLOT_PORT     6
#define SQLDB_SLOT_DBTYPE   7	

#endif
